services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev_sqlserver
    restart: always

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Devops@123*
      - MSSQL_AGENT_ENABLE=true

    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 90 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Devops@123*' -No -i /docker-entrypoint-initdb.d/01-setup.sql &&
      wait
      "

    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - "./seed:/docker-entrypoint-initdb.d"

volumes:
  sqlserver_data:
